mixed-port: 7890
allow-lan: true
mode: rule
log-level: error
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 114.114.114.114
    - 223.5.5.5

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    use:
      - zijian
      - jichang1

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    use:
      - jichang1

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - DIRECT

proxy-providers:
  jichang1:
    type: http
    url: ""                           #å¡«å†™
    interval: 21600
    path: ./jichang1.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  zijian:
    type: file
    path: ./zijian.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ruleset/LocalAreaNetwork.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ruleset/UnBan.yaml
    interval: 86400

  GoogleCN:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml"
    path: ./ruleset/GoogleCN.yaml
    interval: 86400

  SteamCN:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml"
    path: ./ruleset/SteamCN.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400

  ProxyMedia:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml"
    path: ./ruleset/ProxyMedia.yaml
    interval: 86400

  ProxyLite:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml"
    path: ./ruleset/ProxyLite.yaml
    interval: 86400

  ChinaDomain:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ruleset/ChinaDomain.yaml
    interval: 86400

  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml"
    path: ./ruleset/ChinaCompanyIp.yaml
    interval: 86400

rules:
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,UnBan,DIRECT
  - RULE-SET,GoogleCN,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Telegram,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ProxyMedia,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ProxyLite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ChinaCompanyIp,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
